default_platform(:android)

platform :android do
  desc "Android beta distribution"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    firebase_app_distribution(
      app: "1:645714164681:android:b2d2273e001a170895c618",
      testers: "malgorzata.mazurek@callstack.com",
    )
  end
end
