# name: test
# jobs: 
#   runs-on: ubuntu-latest
#   steps:
#     - run: yarn install
#     - run: yarn test

# name: verify
# jobs: 
#   runs-on: ubuntu-latest
#   steps:
#     - run: yarn install
#     - run: yarn lint
#     - run: yarn typecheck


name: On push 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn test
      - run: yarn lint
      - run: yarn typecheck
