name: Verify
on: [push]
jobs:
  on-push-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: verify
