name: Verify
on: [push]
jobs:
  on-push-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install project dependencies
        run: yarn --prefer-offline

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck
